.PHONY: all clean test stack_basic queue_basic list_basic minimal uf_quick_find uf_quick_union uf_weighted_quick_union sort_insertion sort_shell sort_quick sort_merge sort_heap heap_basic bst_basic rbtree_basic hash_linear_probing hash_separate_chaining graph_basic graph_mst digraph_basic digraph_topo

all: stack_basic queue_basic list_basic minimal uf_quick_find uf_quick_union uf_weighted_quick_union sort_insertion sort_shell sort_quick sort_merge sort_heap heap_basic bst_basic rbtree_basic hash_linear_probing hash_separate_chaining graph_basic graph_mst digraph_basic digraph_topo

test: stack_basic queue_basic list_basic minimal uf_quick_find uf_quick_union uf_weighted_quick_union sort_insertion sort_shell sort_quick sort_merge sort_heap heap_basic bst_basic rbtree_basic hash_linear_probing hash_separate_chaining graph_basic graph_mst digraph_basic digraph_topo
	$(MAKE) -C stack_basic test
	$(MAKE) -C queue_basic test
	$(MAKE) -C list_basic test
	$(MAKE) -C minimal test
	$(MAKE) -C uf_quick_find test
	$(MAKE) -C uf_quick_union test
	$(MAKE) -C uf_weighted_quick_union test
	$(MAKE) -C sort_insertion test
	$(MAKE) -C sort_shell test
	$(MAKE) -C sort_quick test
	$(MAKE) -C sort_merge test
	$(MAKE) -C sort_heap test
	$(MAKE) -C heap_basic test
	$(MAKE) -C bst_basic test
	$(MAKE) -C rbtree_basic test
	$(MAKE) -C hash_linear_probing test
	$(MAKE) -C hash_separate_chaining test
	$(MAKE) -C graph_basic test
	$(MAKE) -C graph_mst test
	$(MAKE) -C digraph_basic test
	$(MAKE) -C digraph_topo test

stack_basic:
	$(MAKE) -C stack_basic

queue_basic:
	$(MAKE) -C queue_basic

list_basic:
	$(MAKE) -C list_basic

minimal:
	$(MAKE) -C minimal

uf_quick_find:
	$(MAKE) -C uf_quick_find

uf_quick_union:
	$(MAKE) -C uf_quick_union

uf_weighted_quick_union:
	$(MAKE) -C uf_weighted_quick_union

sort_insertion:
	$(MAKE) -C sort_insertion

sort_shell:
	$(MAKE) -C sort_shell

sort_quick:
	$(MAKE) -C sort_quick

sort_merge:
	$(MAKE) -C sort_merge

sort_heap:
	$(MAKE) -C sort_heap

heap_basic:
	$(MAKE) -C heap_basic

bst_basic:
	$(MAKE) -C bst_basic

rbtree_basic:
	$(MAKE) -C rbtree_basic

hash_linear_probing:
	$(MAKE) -C hash_linear_probing

hash_separate_chaining:
	$(MAKE) -C hash_separate_chaining

graph_basic:
	$(MAKE) -C graph_basic

graph_mst:
	$(MAKE) -C graph_mst

digraph_basic:
	$(MAKE) -C digraph_basic

digraph_topo:
	$(MAKE) -C digraph_topo

clean:
	$(MAKE) -C stack_basic clean
	$(MAKE) -C queue_basic clean
	$(MAKE) -C list_basic clean
	$(MAKE) -C minimal clean
	$(MAKE) -C uf_quick_find clean
	$(MAKE) -C uf_quick_union clean
	$(MAKE) -C uf_weighted_quick_union clean
	$(MAKE) -C sort_insertion clean
	$(MAKE) -C sort_shell clean
	$(MAKE) -C sort_quick clean
	$(MAKE) -C sort_merge clean
	$(MAKE) -C sort_heap clean
	$(MAKE) -C heap_basic clean
	$(MAKE) -C bst_basic clean
	$(MAKE) -C rbtree_basic clean
	$(MAKE) -C hash_linear_probing clean
	$(MAKE) -C hash_separate_chaining clean
	$(MAKE) -C graph_basic clean
	$(MAKE) -C graph_mst clean
	$(MAKE) -C digraph_basic clean
	$(MAKE) -C digraph_topo clean
